/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import * as generated from "../../../schemas";
export type PublicAssignmentStatus = z.infer<
  typeof generated.publicAssignmentStatusSchema
>;
export type PublicCrewType = z.infer<typeof generated.publicCrewTypeSchema>;
export type PublicOutageStatus = z.infer<
  typeof generated.publicOutageStatusSchema
>;
export type PublicOutageType = z.infer<typeof generated.publicOutageTypeSchema>;
export type PublicReportStatus = z.infer<
  typeof generated.publicReportStatusSchema
>;
export type PublicRoles = z.infer<typeof generated.publicRolesSchema>;
export type PublicThemes = z.infer<typeof generated.publicThemesSchema>;
export type Json = z.infer<typeof generated.jsonSchema>;
export type PublicAffectedAreasRow = z.infer<
  typeof generated.publicAffectedAreasRowSchema
>;
export type PublicAffectedAreasInsert = z.infer<
  typeof generated.publicAffectedAreasInsertSchema
>;
export type PublicAffectedAreasUpdate = z.infer<
  typeof generated.publicAffectedAreasUpdateSchema
>;
export type PublicAffectedAreasRelationships = z.infer<
  typeof generated.publicAffectedAreasRelationshipsSchema
>;
export type PublicApiKeysRow = z.infer<typeof generated.publicApiKeysRowSchema>;
export type PublicApiKeysInsert = z.infer<
  typeof generated.publicApiKeysInsertSchema
>;
export type PublicApiKeysUpdate = z.infer<
  typeof generated.publicApiKeysUpdateSchema
>;
export type PublicApiKeysRelationships = z.infer<
  typeof generated.publicApiKeysRelationshipsSchema
>;
export type PublicAssignmentsRow = z.infer<
  typeof generated.publicAssignmentsRowSchema
>;
export type PublicAssignmentsInsert = z.infer<
  typeof generated.publicAssignmentsInsertSchema
>;
export type PublicAssignmentsUpdate = z.infer<
  typeof generated.publicAssignmentsUpdateSchema
>;
export type PublicAssignmentsRelationships = z.infer<
  typeof generated.publicAssignmentsRelationshipsSchema
>;
export type PublicBarangaysRow = z.infer<
  typeof generated.publicBarangaysRowSchema
>;
export type PublicBarangaysInsert = z.infer<
  typeof generated.publicBarangaysInsertSchema
>;
export type PublicBarangaysUpdate = z.infer<
  typeof generated.publicBarangaysUpdateSchema
>;
export type PublicBarangaysRelationships = z.infer<
  typeof generated.publicBarangaysRelationshipsSchema
>;
export type PublicCitiesRow = z.infer<typeof generated.publicCitiesRowSchema>;
export type PublicCitiesInsert = z.infer<
  typeof generated.publicCitiesInsertSchema
>;
export type PublicCitiesUpdate = z.infer<
  typeof generated.publicCitiesUpdateSchema
>;
export type PublicCitiesRelationships = z.infer<
  typeof generated.publicCitiesRelationshipsSchema
>;
export type PublicCrewsRow = z.infer<typeof generated.publicCrewsRowSchema>;
export type PublicCrewsInsert = z.infer<
  typeof generated.publicCrewsInsertSchema
>;
export type PublicCrewsUpdate = z.infer<
  typeof generated.publicCrewsUpdateSchema
>;
export type PublicFeedersRow = z.infer<typeof generated.publicFeedersRowSchema>;
export type PublicFeedersInsert = z.infer<
  typeof generated.publicFeedersInsertSchema
>;
export type PublicFeedersUpdate = z.infer<
  typeof generated.publicFeedersUpdateSchema
>;
export type PublicOutageReportsRow = z.infer<
  typeof generated.publicOutageReportsRowSchema
>;
export type PublicOutageReportsInsert = z.infer<
  typeof generated.publicOutageReportsInsertSchema
>;
export type PublicOutageReportsUpdate = z.infer<
  typeof generated.publicOutageReportsUpdateSchema
>;
export type PublicOutageReportsRelationships = z.infer<
  typeof generated.publicOutageReportsRelationshipsSchema
>;
export type PublicOutageUpdatesRow = z.infer<
  typeof generated.publicOutageUpdatesRowSchema
>;
export type PublicOutageUpdatesInsert = z.infer<
  typeof generated.publicOutageUpdatesInsertSchema
>;
export type PublicOutageUpdatesUpdate = z.infer<
  typeof generated.publicOutageUpdatesUpdateSchema
>;
export type PublicOutageUpdatesRelationships = z.infer<
  typeof generated.publicOutageUpdatesRelationshipsSchema
>;
export type PublicOutagesRow = z.infer<typeof generated.publicOutagesRowSchema>;
export type PublicOutagesInsert = z.infer<
  typeof generated.publicOutagesInsertSchema
>;
export type PublicOutagesUpdate = z.infer<
  typeof generated.publicOutagesUpdateSchema
>;
export type PublicOutagesRelationships = z.infer<
  typeof generated.publicOutagesRelationshipsSchema
>;
export type PublicProfileSettingsRow = z.infer<
  typeof generated.publicProfileSettingsRowSchema
>;
export type PublicProfileSettingsInsert = z.infer<
  typeof generated.publicProfileSettingsInsertSchema
>;
export type PublicProfileSettingsUpdate = z.infer<
  typeof generated.publicProfileSettingsUpdateSchema
>;
export type PublicProfileSettingsRelationships = z.infer<
  typeof generated.publicProfileSettingsRelationshipsSchema
>;
export type PublicProfilesRow = z.infer<
  typeof generated.publicProfilesRowSchema
>;
export type PublicProfilesInsert = z.infer<
  typeof generated.publicProfilesInsertSchema
>;
export type PublicProfilesUpdate = z.infer<
  typeof generated.publicProfilesUpdateSchema
>;
export type PublicProvincesRow = z.infer<
  typeof generated.publicProvincesRowSchema
>;
export type PublicProvincesInsert = z.infer<
  typeof generated.publicProvincesInsertSchema
>;
export type PublicProvincesUpdate = z.infer<
  typeof generated.publicProvincesUpdateSchema
>;
export type PublicSystemConfigRow = z.infer<
  typeof generated.publicSystemConfigRowSchema
>;
export type PublicSystemConfigInsert = z.infer<
  typeof generated.publicSystemConfigInsertSchema
>;
export type PublicSystemConfigUpdate = z.infer<
  typeof generated.publicSystemConfigUpdateSchema
>;
export type PublicSystemConfigRelationships = z.infer<
  typeof generated.publicSystemConfigRelationshipsSchema
>;
export type PublicWeatherDataRow = z.infer<
  typeof generated.publicWeatherDataRowSchema
>;
export type PublicWeatherDataInsert = z.infer<
  typeof generated.publicWeatherDataInsertSchema
>;
export type PublicWeatherDataUpdate = z.infer<
  typeof generated.publicWeatherDataUpdateSchema
>;
export type PublicWeatherDataRelationships = z.infer<
  typeof generated.publicWeatherDataRelationshipsSchema
>;
export type PublicOutageSummaryRow = z.infer<
  typeof generated.publicOutageSummaryRowSchema
>;
