/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import { type Json } from "../types";

export const publicAssignmentStatusSchema = z.union([
  z.literal("assigned"),
  z.literal("en_route"),
  z.literal("on_site"),
  z.literal("paused"),
  z.literal("completed"),
  z.literal("cancelled"),
]);

export const publicCrewTypeSchema = z.union([
  z.literal("team"),
  z.literal("individual"),
]);

export const publicOutageStatusSchema = z.union([
  z.literal("unverified"),
  z.literal("verified"),
  z.literal("being_resolved"),
  z.literal("resolved"),
]);

export const publicOutageTypeSchema = z.union([
  z.literal("unscheduled"),
  z.literal("scheduled"),
  z.literal("emergency"),
]);

export const publicReportStatusSchema = z.union([
  z.literal("unprocessed"),
  z.literal("processed_as_new_outage"),
  z.literal("processed_as_duplicate"),
  z.literal("archived_as_isolated"),
]);

export const publicRolesSchema = z.union([
  z.literal("user"),
  z.literal("crew"),
  z.literal("admin"),
]);

export const publicThemesSchema = z.union([
  z.literal("light"),
  z.literal("dark"),
  z.literal("system"),
]);

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const publicAffectedAreasRowSchema = z.object({
  barangay_id: z.number(),
  created_at: z.string(),
  id: z.number(),
  outage_id: z.number(),
});

export const publicAffectedAreasInsertSchema = z.object({
  barangay_id: z.number(),
  created_at: z.string().optional(),
  id: z.number().optional(),
  outage_id: z.number(),
});

export const publicAffectedAreasUpdateSchema = z.object({
  barangay_id: z.number().optional(),
  created_at: z.string().optional(),
  id: z.number().optional(),
  outage_id: z.number().optional(),
});

export const publicAffectedAreasRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("affected_areas_barangay_id_fkey"),
    columns: z.tuple([z.literal("barangay_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("barangays"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("affected_areas_outage_id_fkey"),
    columns: z.tuple([z.literal("outage_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("outage_summary"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("affected_areas_outage_id_fkey"),
    columns: z.tuple([z.literal("outage_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("outages"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicApiKeysRowSchema = z.object({
  api_key: z.string(),
  created_at: z.string(),
  created_by: z.number().nullable(),
  expires_at: z.string().nullable(),
  id: z.number(),
  is_active: z.boolean(),
  name: z.string(),
  public_id: z.string(),
  rate_limit_per_minute: z.number().nullable(),
  secret_key: z.string().nullable(),
  service_name: z.string().nullable(),
});

export const publicApiKeysInsertSchema = z.object({
  api_key: z.string(),
  created_at: z.string().optional(),
  created_by: z.number().optional().nullable(),
  expires_at: z.string().optional().nullable(),
  id: z.number().optional(),
  is_active: z.boolean().optional(),
  name: z.string(),
  public_id: z.string().optional(),
  rate_limit_per_minute: z.number().optional().nullable(),
  secret_key: z.string().optional().nullable(),
  service_name: z.string().optional().nullable(),
});

export const publicApiKeysUpdateSchema = z.object({
  api_key: z.string().optional(),
  created_at: z.string().optional(),
  created_by: z.number().optional().nullable(),
  expires_at: z.string().optional().nullable(),
  id: z.number().optional(),
  is_active: z.boolean().optional(),
  name: z.string().optional(),
  public_id: z.string().optional(),
  rate_limit_per_minute: z.number().optional().nullable(),
  secret_key: z.string().optional().nullable(),
  service_name: z.string().optional().nullable(),
});

export const publicApiKeysRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("api_keys_created_by_fkey"),
    columns: z.tuple([z.literal("created_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicAssignmentsRowSchema = z.object({
  assigned_at: z.string(),
  crew_id: z.number(),
  id: z.number(),
  notes: z.string().nullable(),
  outage_id: z.number(),
  public_id: z.string(),
  status: publicAssignmentStatusSchema,
  updated_at: z.string().nullable(),
});

export const publicAssignmentsInsertSchema = z.object({
  assigned_at: z.string().optional(),
  crew_id: z.number(),
  id: z.number().optional(),
  notes: z.string().optional().nullable(),
  outage_id: z.number(),
  public_id: z.string().optional(),
  status: publicAssignmentStatusSchema.optional(),
  updated_at: z.string().optional().nullable(),
});

export const publicAssignmentsUpdateSchema = z.object({
  assigned_at: z.string().optional(),
  crew_id: z.number().optional(),
  id: z.number().optional(),
  notes: z.string().optional().nullable(),
  outage_id: z.number().optional(),
  public_id: z.string().optional(),
  status: publicAssignmentStatusSchema.optional(),
  updated_at: z.string().optional().nullable(),
});

export const publicAssignmentsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("assignments_crew_id_fkey"),
    columns: z.tuple([z.literal("crew_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("crews"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("assignments_outage_id_fkey"),
    columns: z.tuple([z.literal("outage_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("outage_summary"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("assignments_outage_id_fkey"),
    columns: z.tuple([z.literal("outage_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("outages"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicBarangaysRowSchema = z.object({
  boundary: z.unknown(),
  city_id: z.number(),
  created_at: z.string(),
  feeder_id: z.number().nullable(),
  id: z.number(),
  name: z.string(),
  population: z.number().nullable(),
  population_year: z.number().nullable(),
  public_id: z.string(),
  updated_at: z.string().nullable(),
});

export const publicBarangaysInsertSchema = z.object({
  boundary: z.unknown(),
  city_id: z.number(),
  created_at: z.string().optional(),
  feeder_id: z.number().optional().nullable(),
  id: z.number().optional(),
  name: z.string(),
  population: z.number().optional().nullable(),
  population_year: z.number().optional().nullable(),
  public_id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
});

export const publicBarangaysUpdateSchema = z.object({
  boundary: z.unknown().optional(),
  city_id: z.number().optional(),
  created_at: z.string().optional(),
  feeder_id: z.number().optional().nullable(),
  id: z.number().optional(),
  name: z.string().optional(),
  population: z.number().optional().nullable(),
  population_year: z.number().optional().nullable(),
  public_id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
});

export const publicBarangaysRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("barangays_city_id_fkey"),
    columns: z.tuple([z.literal("city_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("cities"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("barangays_feeder_id_fkey"),
    columns: z.tuple([z.literal("feeder_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("feeders"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicCitiesRowSchema = z.object({
  boundary: z.unknown(),
  created_at: z.string(),
  id: z.number(),
  name: z.string(),
  population: z.number().nullable(),
  population_year: z.number().nullable(),
  province_id: z.number(),
  public_id: z.string(),
  updated_at: z.string().nullable(),
});

export const publicCitiesInsertSchema = z.object({
  boundary: z.unknown(),
  created_at: z.string().optional(),
  id: z.number().optional(),
  name: z.string(),
  population: z.number().optional().nullable(),
  population_year: z.number().optional().nullable(),
  province_id: z.number(),
  public_id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
});

export const publicCitiesUpdateSchema = z.object({
  boundary: z.unknown().optional(),
  created_at: z.string().optional(),
  id: z.number().optional(),
  name: z.string().optional(),
  population: z.number().optional().nullable(),
  population_year: z.number().optional().nullable(),
  province_id: z.number().optional(),
  public_id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
});

export const publicCitiesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("cities_province_id_fkey"),
    columns: z.tuple([z.literal("province_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("provinces"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicCrewsRowSchema = z.object({
  created_at: z.string(),
  crew_type: publicCrewTypeSchema,
  description: z.string().nullable(),
  id: z.number(),
  name: z.string(),
  public_id: z.string(),
  updated_at: z.string().nullable(),
});

export const publicCrewsInsertSchema = z.object({
  created_at: z.string().optional(),
  crew_type: publicCrewTypeSchema.optional(),
  description: z.string().optional().nullable(),
  id: z.number().optional(),
  name: z.string(),
  public_id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
});

export const publicCrewsUpdateSchema = z.object({
  created_at: z.string().optional(),
  crew_type: publicCrewTypeSchema.optional(),
  description: z.string().optional().nullable(),
  id: z.number().optional(),
  name: z.string().optional(),
  public_id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
});

export const publicFeedersRowSchema = z.object({
  boundary: z.unknown(),
  created_at: z.string(),
  feeder_number: z.number(),
  id: z.number(),
  public_id: z.string(),
  updated_at: z.string().nullable(),
});

export const publicFeedersInsertSchema = z.object({
  boundary: z.unknown(),
  created_at: z.string().optional(),
  feeder_number: z.number(),
  id: z.number().optional(),
  public_id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
});

export const publicFeedersUpdateSchema = z.object({
  boundary: z.unknown().optional(),
  created_at: z.string().optional(),
  feeder_number: z.number().optional(),
  id: z.number().optional(),
  public_id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
});

export const publicOutageReportsRowSchema = z.object({
  description: z.string().nullable(),
  id: z.number(),
  image_url: z.string().nullable(),
  linked_outage_id: z.number().nullable(),
  location: z.unknown(),
  public_id: z.string(),
  reported_at: z.string(),
  reported_by: z.number().nullable(),
  status: publicReportStatusSchema,
  updated_at: z.string().nullable(),
});

export const publicOutageReportsInsertSchema = z.object({
  description: z.string().optional().nullable(),
  id: z.number().optional(),
  image_url: z.string().optional().nullable(),
  linked_outage_id: z.number().optional().nullable(),
  location: z.unknown(),
  public_id: z.string().optional(),
  reported_at: z.string().optional(),
  reported_by: z.number().optional().nullable(),
  status: publicReportStatusSchema.optional(),
  updated_at: z.string().optional().nullable(),
});

export const publicOutageReportsUpdateSchema = z.object({
  description: z.string().optional().nullable(),
  id: z.number().optional(),
  image_url: z.string().optional().nullable(),
  linked_outage_id: z.number().optional().nullable(),
  location: z.unknown().optional(),
  public_id: z.string().optional(),
  reported_at: z.string().optional(),
  reported_by: z.number().optional().nullable(),
  status: publicReportStatusSchema.optional(),
  updated_at: z.string().optional().nullable(),
});

export const publicOutageReportsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("outage_reports_linked_outage_id_fkey"),
    columns: z.tuple([z.literal("linked_outage_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("outage_summary"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("outage_reports_linked_outage_id_fkey"),
    columns: z.tuple([z.literal("linked_outage_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("outages"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("outage_reports_reported_by_fkey"),
    columns: z.tuple([z.literal("reported_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicOutageUpdatesRowSchema = z.object({
  created_at: z.string(),
  description: z.string().nullable(),
  id: z.number(),
  new_status: publicOutageStatusSchema,
  old_status: publicOutageStatusSchema,
  outage_id: z.number(),
  public_id: z.string(),
  user_id: z.number(),
});

export const publicOutageUpdatesInsertSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.number().optional(),
  new_status: publicOutageStatusSchema,
  old_status: publicOutageStatusSchema,
  outage_id: z.number(),
  public_id: z.string().optional(),
  user_id: z.number(),
});

export const publicOutageUpdatesUpdateSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.number().optional(),
  new_status: publicOutageStatusSchema.optional(),
  old_status: publicOutageStatusSchema.optional(),
  outage_id: z.number().optional(),
  public_id: z.string().optional(),
  user_id: z.number().optional(),
});

export const publicOutageUpdatesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("outage_updates_outage_id_fkey"),
    columns: z.tuple([z.literal("outage_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("outage_summary"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("outage_updates_outage_id_fkey"),
    columns: z.tuple([z.literal("outage_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("outages"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("outage_updates_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicOutagesRowSchema = z.object({
  actual_restoration_time: z.string().nullable(),
  confidence_percentage: z.number().nullable(),
  confirmed_by: z.number().nullable(),
  created_at: z.string(),
  description: z.string().nullable(),
  estimated_affected_population: z.number().nullable(),
  estimated_restoration_time: z.string().nullable(),
  id: z.number(),
  number_of_reports: z.number().nullable(),
  outage_type: publicOutageTypeSchema,
  public_id: z.string(),
  resolved_by: z.number().nullable(),
  start_time: z.string().nullable(),
  status: publicOutageStatusSchema,
  title: z.string().nullable(),
  updated_at: z.string().nullable(),
});

export const publicOutagesInsertSchema = z.object({
  actual_restoration_time: z.string().optional().nullable(),
  confidence_percentage: z.number().optional().nullable(),
  confirmed_by: z.number().optional().nullable(),
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  estimated_affected_population: z.number().optional().nullable(),
  estimated_restoration_time: z.string().optional().nullable(),
  id: z.number().optional(),
  number_of_reports: z.number().optional().nullable(),
  outage_type: publicOutageTypeSchema.optional(),
  public_id: z.string().optional(),
  resolved_by: z.number().optional().nullable(),
  start_time: z.string().optional().nullable(),
  status: publicOutageStatusSchema.optional(),
  title: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
});

export const publicOutagesUpdateSchema = z.object({
  actual_restoration_time: z.string().optional().nullable(),
  confidence_percentage: z.number().optional().nullable(),
  confirmed_by: z.number().optional().nullable(),
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  estimated_affected_population: z.number().optional().nullable(),
  estimated_restoration_time: z.string().optional().nullable(),
  id: z.number().optional(),
  number_of_reports: z.number().optional().nullable(),
  outage_type: publicOutageTypeSchema.optional(),
  public_id: z.string().optional(),
  resolved_by: z.number().optional().nullable(),
  start_time: z.string().optional().nullable(),
  status: publicOutageStatusSchema.optional(),
  title: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
});

export const publicOutagesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("outages_confirmed_by_fkey"),
    columns: z.tuple([z.literal("confirmed_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("outages_resolved_by_fkey"),
    columns: z.tuple([z.literal("resolved_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicProfileSettingsRowSchema = z.object({
  created_at: z.string(),
  dynamic_color: z.boolean(),
  extra_settings: jsonSchema,
  font_scale: z.number(),
  id: z.number(),
  language: z.string(),
  profile_id: z.number().nullable(),
  reduce_motion: z.boolean(),
  theme: publicThemesSchema,
  updated_at: z.string().nullable(),
});

export const publicProfileSettingsInsertSchema = z.object({
  created_at: z.string().optional(),
  dynamic_color: z.boolean().optional(),
  extra_settings: jsonSchema.optional(),
  font_scale: z.number().optional(),
  id: z.number().optional(),
  language: z.string().optional(),
  profile_id: z.number().optional().nullable(),
  reduce_motion: z.boolean().optional(),
  theme: publicThemesSchema.optional(),
  updated_at: z.string().optional().nullable(),
});

export const publicProfileSettingsUpdateSchema = z.object({
  created_at: z.string().optional(),
  dynamic_color: z.boolean().optional(),
  extra_settings: jsonSchema.optional(),
  font_scale: z.number().optional(),
  id: z.number().optional(),
  language: z.string().optional(),
  profile_id: z.number().optional().nullable(),
  reduce_motion: z.boolean().optional(),
  theme: publicThemesSchema.optional(),
  updated_at: z.string().optional().nullable(),
});

export const publicProfileSettingsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("profile_settings_profile_id_fkey"),
    columns: z.tuple([z.literal("profile_id")]),
    isOneToOne: z.literal(true),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicProfilesRowSchema = z.object({
  created_at: z.string(),
  first_name: z.string(),
  id: z.number(),
  last_name: z.string(),
  phone_number: z.string().nullable(),
  public_id: z.string(),
  role: publicRolesSchema,
  updated_at: z.string().nullable(),
  user_id: z.string(),
});

export const publicProfilesInsertSchema = z.object({
  created_at: z.string().optional(),
  first_name: z.string(),
  id: z.number().optional(),
  last_name: z.string(),
  phone_number: z.string().optional().nullable(),
  public_id: z.string().optional(),
  role: publicRolesSchema.optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string(),
});

export const publicProfilesUpdateSchema = z.object({
  created_at: z.string().optional(),
  first_name: z.string().optional(),
  id: z.number().optional(),
  last_name: z.string().optional(),
  phone_number: z.string().optional().nullable(),
  public_id: z.string().optional(),
  role: publicRolesSchema.optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const publicProvincesRowSchema = z.object({
  boundary: z.unknown(),
  created_at: z.string(),
  id: z.number(),
  name: z.string(),
  population: z.number().nullable(),
  population_year: z.number().nullable(),
  public_id: z.string(),
  updated_at: z.string().nullable(),
});

export const publicProvincesInsertSchema = z.object({
  boundary: z.unknown(),
  created_at: z.string().optional(),
  id: z.number().optional(),
  name: z.string(),
  population: z.number().optional().nullable(),
  population_year: z.number().optional().nullable(),
  public_id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
});

export const publicProvincesUpdateSchema = z.object({
  boundary: z.unknown().optional(),
  created_at: z.string().optional(),
  id: z.number().optional(),
  name: z.string().optional(),
  population: z.number().optional().nullable(),
  population_year: z.number().optional().nullable(),
  public_id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
});

export const publicSystemConfigRowSchema = z.object({
  description: z.string().nullable(),
  id: z.number(),
  key: z.string(),
  public_id: z.string(),
  updated_at: z.string().nullable(),
  updated_by: z.number().nullable(),
  value: z.string(),
});

export const publicSystemConfigInsertSchema = z.object({
  description: z.string().optional().nullable(),
  id: z.number().optional(),
  key: z.string(),
  public_id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  updated_by: z.number().optional().nullable(),
  value: z.string(),
});

export const publicSystemConfigUpdateSchema = z.object({
  description: z.string().optional().nullable(),
  id: z.number().optional(),
  key: z.string().optional(),
  public_id: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  updated_by: z.number().optional().nullable(),
  value: z.string().optional(),
});

export const publicSystemConfigRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("system_config_updated_by_fkey"),
    columns: z.tuple([z.literal("updated_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("profiles"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicWeatherDataRowSchema = z.object({
  atmospheric_pressure: z.number().nullable(),
  city_id: z.number(),
  condition_description: z.string().nullable(),
  condition_main: z.string().nullable(),
  created_at: z.string(),
  feels_like: z.number().nullable(),
  humidity: z.number().nullable(),
  id: z.number(),
  precipitation: z.number().nullable(),
  public_id: z.string(),
  recorded_at: z.string(),
  temperature: z.number(),
  wind_speed: z.number().nullable(),
});

export const publicWeatherDataInsertSchema = z.object({
  atmospheric_pressure: z.number().optional().nullable(),
  city_id: z.number(),
  condition_description: z.string().optional().nullable(),
  condition_main: z.string().optional().nullable(),
  created_at: z.string().optional(),
  feels_like: z.number().optional().nullable(),
  humidity: z.number().optional().nullable(),
  id: z.number().optional(),
  precipitation: z.number().optional().nullable(),
  public_id: z.string().optional(),
  recorded_at: z.string(),
  temperature: z.number(),
  wind_speed: z.number().optional().nullable(),
});

export const publicWeatherDataUpdateSchema = z.object({
  atmospheric_pressure: z.number().optional().nullable(),
  city_id: z.number().optional(),
  condition_description: z.string().optional().nullable(),
  condition_main: z.string().optional().nullable(),
  created_at: z.string().optional(),
  feels_like: z.number().optional().nullable(),
  humidity: z.number().optional().nullable(),
  id: z.number().optional(),
  precipitation: z.number().optional().nullable(),
  public_id: z.string().optional(),
  recorded_at: z.string().optional(),
  temperature: z.number().optional(),
  wind_speed: z.number().optional().nullable(),
});

export const publicWeatherDataRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("weather_data_city_id_fkey"),
    columns: z.tuple([z.literal("city_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("cities"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicOutageSummaryRowSchema = z.object({
  affected_barangay_count: z.number().nullable(),
  estimated_population_affected: z.number().nullable(),
  id: z.number().nullable(),
  public_id: z.string().nullable(),
  status: publicOutageStatusSchema.nullable(),
});
